version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-ecs: circleci/aws-ecs@3.2.0
  node: circleci/node@5.1.0

jobs:
  test:
    docker:
      - image: cimg/node:18.19
        environment:
          NODE_ENV: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            npm install --legacy-peer-deps
            cd frontend && npm install --legacy-peer-deps
      - save_cache:
          paths:
            - node_modules
            - frontend/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Tests
          command: npm run test:ci
          no_output_timeout: 5m

workflows:
  build-test-deploy:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          name: build-and-push-backend
          requires:
            - test
          create-repo: true
          repo: quiz-dock-backend
          region: ${AWS_REGION}
          tag: latest,${CIRCLE_SHA1}
          path: ./
          dockerfile: Dockerfile
      - aws-ecr/build-and-push-image:
          name: build-and-push-frontend
          requires:
            - test
          create-repo: true
          repo: quiz-dock-frontend
          region: ${AWS_REGION}
          tag: latest,${CIRCLE_SHA1}
          path: ./frontend
          dockerfile: Dockerfile
      - aws-ecs/deploy-service-update:
          requires:
            - build-and-push-backend
            - build-and-push-frontend
          family: quiz-dock-service
          cluster: quiz-dock-cluster
          container-image-name-updates: "container=quiz-dock-backend,tag=${CIRCLE_SHA1},container=quiz-dock-frontend,tag=${CIRCLE_SHA1}" 