version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-ecs: circleci/aws-ecs@3.2.0
  node: circleci/node@5.1.0

jobs:
  test:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run backend tests
          command: npm run test:ci

workflows:
  build-test-deploy:
    jobs:
      - test
      - aws-ecr/build-and-push-image:
          name: build-and-push-backend
          requires:
            - test
          repo: "${AWS_RESOURCE_NAME_PREFIX}-backend"
          path: ./
          tag: "${CIRCLE_SHA1}"
      - aws-ecr/build-and-push-image:
          name: build-and-push-frontend
          requires:
            - test
          repo: "${AWS_RESOURCE_NAME_PREFIX}-frontend"
          path: ./frontend
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          requires:
            - build-and-push-backend
            - build-and-push-frontend
          family: "${AWS_RESOURCE_NAME_PREFIX}-service"
          cluster: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
          container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-backend,tag=${CIRCLE_SHA1},container=${AWS_RESOURCE_NAME_PREFIX}-frontend,tag=${CIRCLE_SHA1}" 