version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@3.2.0
  node: circleci/node@5.1.0

jobs:
  test:
    docker:
      - image: cimg/node:18.19
        environment:
          NODE_ENV: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            npm install --legacy-peer-deps
            cd frontend && npm install --legacy-peer-deps
      - save_cache:
          paths:
            - node_modules
            - frontend/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Tests
          command: npm run test:ci
          no_output_timeout: 5m

  build-and-push-backend:
    docker:
      - image: cimg/aws:2024.03
    steps:
      - checkout
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          create-repo: true
          repo: ${AWS_ECR_BACKEND_REPO}
          region: AWS_DEFAULT_REGION
          tag: latest,${CIRCLE_SHA1}
          dockerfile: Dockerfile
          path: ./
          extra-build-args: --platform=linux/amd64

  build-and-push-frontend:
    docker:
      - image: cimg/aws:2024.03
    steps:
      - checkout
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          create-repo: true
          repo: ${AWS_ECR_FRONTEND_REPO}
          region: AWS_DEFAULT_REGION
          tag: latest,${CIRCLE_SHA1}
          dockerfile: Dockerfile
          path: ./frontend
          extra-build-args: --platform=linux/amd64

workflows:
  build-test-deploy:
    jobs:
      - test
      - build-and-push-backend:
          requires:
            - test
      - build-and-push-frontend:
          requires:
            - test
      - aws-ecs/deploy-service-update:
          requires:
            - build-and-push-backend
            - build-and-push-frontend
          family: ${AWS_ECS_CLUSTER}
          cluster: ${AWS_ECS_CLUSTER}
          container-image-name-updates: "container=quiz-dock-backend,tag=${CIRCLE_SHA1},container=quiz-dock-frontend,tag=${CIRCLE_SHA1}" 